services:

  db-simplebank:
    container_name: db-simplebank
    image: postgres:14.0-alpine   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data # Persists data in a named volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    